list = ['luigui', 'victor', 'wesley', 'miller']
print(list)
list.append('matheus')
print(list)
list.pop()
print(list)
list.remove('wesley')
print(list)
list.insert(0, 'ravena')
print(list)
del list[1]
print(list)
list.sort()
print(list)
list.reverse()
print(list)
print(sorted(list))
print(list)
print(len(list))
